services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    command: uvicorn server:app --host 0.0.0.0 --port 8000 --reload
    environment:
      MONGO_URI: mongodb://mongo:27017/emergent
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      CORS_ORIGINS: ${CORS_ORIGINS:-*}
    depends_on: [mongo]
    ports: ["8000:8000"]
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    command: npm run dev -- --host --port 5173
    environment:
      VITE_API_URL: http://localhost:8000
    ports: ["5173:5173"]
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mongo_data:
